<?php
if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['label'] = [
    'electricity' => 'Điện',
    'water' => 'Nước',
    'internet' => 'Internet',
    'note' => 'Ghi chú',
    'elevator' => 'Thang máy',
    'washing_machine' => 'Máy giặt',
    'room_cleaning' => 'Dọn phòng',
    'parking' => 'Bãi đậu xe',
    'car_park' => 'Bãi xe Ô tô',
    'commission_rate' => 'Hoa Hồng (12th)',
    'commission_rate_6m' => 'Hoa Hồng (6th)',
    'commission_rate_9m' => 'Hoa Hồng (9th)',
    'deposit' => 'Cọc',
    'number_of_people' => 'Số người ở',
    'kitchen' => 'Bếp',
    'contract_long_term' => 'Ký dài hạn',
    'contract_short_term' => 'Ký ngắn hạn',
    'sofa' => 'Ghế Sofa',
    'security' => 'Bảo vệ',
    'management_fee' => 'Ra vào',
    'extra_fee' => 'Combo Phí',
    'east' => 'Đông',
    'west' => 'Tây',
    'south' => 'Nam',
    'north' => 'Bắc',
    'male' => 'Nam',
    'female' => 'Nữ',
    'east-south' => 'Đông Nam',
    'west-south' => 'Tây Nam',
    'status-full' => 'full',
    'status-available' => 'trống',
    'status-pending' => 'chờ duyệt',
    'status-expired' => 'hết hạn',
    'status-cancel' => 'đã huỷ',
    'apartment' => 'căn hộ',
    'contract' => 'hợp đồng',
    'deposit-doc' => 'giấy cọc',
    'commission-billing' => 'phiếu thu hoa hồng',
    'customer' => 'khách thuê',
    'district' => 'quận',
    'time_check_in' => 'ngày ký',
    'time_expire' => 'ngày hết hạn',
    'number_of_month' => 'số tháng',
    'revenue_amount' => 'doanh thu',
    'sales_amount' => 'doanh số',
    'quantity' => 'số lượng',
    'member' => 'nhân sự',
    'leader' => 'leader',
    'team' => 'đội nhóm',
    'ward' => 'phường',

    'account' => 'Tài khoản',
    'change_password' => 'Đổi mật khẩu',
    'logout' => 'Đăng xuất',
];
?>
